---
OrdererOrgs:
  - Name: OrdererOrg
    Domain: ehr.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer
    Users:
      Count: 1

PeerOrgs:
  - Name: HospitalOrg
    Domain: hospital.ehr.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 3

  - Name: PatientOrg
    Domain: patient.ehr.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 3
